name: 'Auto-assign Issue'
description: 'Auto-assigns issues to a user'
inputs:
    user:
        description: 'User that will be assigned to the issue'
        required: true

runs:
    using: 'node12'
    main: 'src/index.js'
