name: 'Auto-assign Issue'
description: 'Auto-assigns issues to users'
inputs:
    assignees:
        description: 'Comma separated list of user names'
        required: true

runs:
    using: 'node12'
    main: 'src/index.js'

branding:
    icon: 'alert-circle'
    color: 'red'
